const LANGUAGES = {
  "af-ZA": "Afrikaans",
  "am-ET": "Amharic",
  "ar-SA": "Arabic",
  "az-AZ": "Azerbaijani",
  "be-BY": "Belarusian",
  "bg-BG": "Bulgarian",
  "bn-BD": "Bengali",
  "bs-BA": "Bosnian",
  "ca-ES": "Catalan",
  "ceb-PH": "Cebuano",
  "co-FR": "Corsican",
  "cs-CZ": "Czech",
  "cy-GB": "Welsh",
  "da-DK": "Danish",
  "de-DE": "German",
  "el-GR": "Greek",
  "en-US": "English (US)",
  "en-GB": "English (UK)",
  "eo-EU": "Esperanto",
  "es-ES": "Spanish (Spain)",
  "es-MX": "Spanish (Mexico)",
  "et-EE": "Estonian",
  "eu-ES": "Basque",
  "fa-IR": "Persian (Farsi)",
  "fi-FI": "Finnish",
  "fr-FR": "French",
  "fr-CA": "French (Canada)",
  "fy-NL": "Frisian",
  "ga-IE": "Irish",
  "gd-GB": "Scottish Gaelic",
  "gl-ES": "Galician",
  "gu-IN": "Gujarati",
  "ha-NG": "Hausa",
  "haw-US": "Hawaiian",
  "he-IL": "Hebrew",
  "hi-IN": "Hindi",
  "hmn-CN": "Hmong",
  "hr-HR": "Croatian",
  "ht-HT": "Haitian Creole",
  "hu-HU": "Hungarian",
  "hy-AM": "Armenian",
  "id-ID": "Indonesian",
  "ig-NG": "Igbo",
  "is-IS": "Icelandic",
  "it-IT": "Italian",
  "ja-JP": "Japanese",
  "jv-ID": "Javanese",
  "ka-GE": "Georgian",
  "kk-KZ": "Kazakh",
  "km-KH": "Khmer",
  "kn-IN": "Kannada",
  "ko-KR": "Korean",
  "ku-TR": "Kurdish",
  "ky-KG": "Kyrgyz",
  "la-VA": "Latin",
  "lb-LU": "Luxembourgish",
  "lo-LA": "Lao",
  "lt-LT": "Lithuanian",
  "lv-LV": "Latvian",
  "mg-MG": "Malagasy",
  "mi-NZ": "Māori",
  "mk-MK": "Macedonian",
  "ml-IN": "Malayalam",
  "mn-MN": "Mongolian",
  "mr-IN": "Marathi",
  "ms-MY": "Malay",
  "mt-MT": "Maltese",
  "my-MM": "Burmese",
  "ne-NP": "Nepali",
  "nl-NL": "Dutch",
  "no-NO": "Norwegian",
  "ny-MW": "Chichewa",
  "or-IN": "Odia",
  "pa-IN": "Punjabi",
  "pl-PL": "Polish",
  "ps-AF": "Pashto",
  "pt-PT": "Portuguese (Portugal)",
  "pt-BR": "Portuguese (Brazil)",
  "ro-RO": "Romanian",
  "ru-RU": "Russian",
  "sd-PK": "Sindhi",
  "si-LK": "Sinhala",
  "sk-SK": "Slovak",
  "sl-SI": "Slovenian",
  "sm-WS": "Samoan",
  "sn-ZW": "Shona",
  "so-SO": "Somali",
  "sq-AL": "Albanian",
  "sr-RS": "Serbian",
  "st-ZA": "Sesotho",
  "su-ID": "Sundanese",
  "sv-SE": "Swedish",
  "sw-KE": "Swahili",
  "ta-IN": "Tamil",
  "te-IN": "Telugu",
  "tg-TJ": "Tajik",
  "th-TH": "Thai",
  "tl-PH": "Tagalog",
  "tr-TR": "Turkish",
  "ug-CN": "Uyghur",
  "uk-UA": "Ukrainian",
  "ur-PK": "Urdu",
  "uz-UZ": "Uzbek",
  "vi-VN": "Vietnamese",
  "xh-ZA": "Xhosa",
  "yi-YD": "Yiddish",
  "yo-NG": "Yoruba",
  "zh-CN": "Chinese (Simplified)",
  "zh-TW": "Chinese (Traditional)",
  "zu-ZA": "Zulu",
};

export default LANGUAGES;
